# Generated by Django 3.1 on 2021-05-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seedling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_input', models.DateTimeField(auto_now_add=True)),
                ('local_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('nursery', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('seedling_img', models.ImageField(blank=True, null=True, upload_to='seedling_img/', verbose_name='Seedling Image')),
            ],
            options={
                'ordering': ['-date_input'],
            },
        ),
    ]
