# Generated by Django 3.1 on 2021-01-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_first_name', models.CharField(max_length=250)),
                ('subscriber_last_name', models.CharField(max_length=250)),
                ('subscriber_email', models.EmailField(max_length=255)),
                ('subscribe_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
