# Generated by Django 3.1 on 2021-06-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantingProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('program_date', models.CharField(max_length=50)),
                ('program_name', models.CharField(max_length=200)),
                ('program_location', models.CharField(max_length=100)),
                ('program_area', models.FloatField()),
                ('program_species', models.CharField(max_length=200)),
                ('program_participant', models.CharField(max_length=200)),
                ('programme_img', models.ImageField(blank=True, null=True, upload_to='program_img/', verbose_name='Program Image')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
