# Generated by Django 3.1 on 2021-06-01 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantingprogram',
            old_name='programme_img',
            new_name='program_img',
        ),
    ]
