# Generated by Django 3.1 on 2021-06-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planting', '0002_auto_20210601_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_presented', models.DateTimeField(auto_now_add=True)),
                ('item_local_name', models.CharField(max_length=100)),
                ('item_scientific_name', models.CharField(max_length=100)),
                ('item_img', models.ImageField(blank=True, null=True, upload_to='item_img/', verbose_name='Item Image')),
            ],
            options={
                'ordering': ['-date_presented'],
            },
        ),
    ]
